<!--get Current User Email-->
<?php $userHelper = $this->plugin('user'); ?>
<?php $user = $userHelper->current();?>

<div class="user-profile pull-right">
    <div class="user-logo">
        <img src="/uploads/user/<?=$user->getId() .'/' . $user->getPhoto();?>" alt="">
    </div>
    <div class="user-name">
        <h6><?=$user->getFio()?></h6>
        <span><?=$user->getEmail()?></span>
    </div>
    <a href="#" onclick="if(confirm('Выйти?')) document.location.href='<?= $this->url('default', ['controller' => 'user','action' => 'logout'])?>,'" class="logout-btn">
        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
</div>