Agere\User\Model\User:
  type: entity
  table: user
  repositoryClass: Agere\User\Model\Repository\UserRepository
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
      options:
        unsigned: true
    departmentId:
      type: integer
      options:
        unsigned: true
      nullable: true
    supplierId:
      type: integer
      options:
        unsigned: true
        default: 0
        comment: Поставщик
    email:
     type: string
     length: 100
    password:
      type: string
      length: 32
    fio:
      type: string
      length: 30
    lastName:
      type: string
      length: 30
    patronymic:
      type: string
      length: 50
    phone:
      type: string
      length: 20
    phoneWork:
      type: string
      length: 20
    phoneInternal:
      type: string
      length: 20
    dateBirth:
      type: date
      nullable: true
      options:
        comment: День рождения
    dateEmployment:
      type: date
      nullable: true
      options:
        comment: Дата принятия на работу
    photo:
      type: string
      nullable: true
      length: 255
    notation:
      type: text
      nullable: true
    showIndex:
      type: string
      length: 255
      nullable: true
      options:
        default: city
        comment: Доступні значення city, supplier
    sendEmails:
      type: integer
      nullable: true
    remove:
      type: integer
      nullable: true
  manyToMany:
    #cities: # unidirectional @link http://goo.gl/xqnlAl
    #  targetEntity: Magere\City\Model\City
    #  joinTable:
    #    name: users_cities
    #    joinColumns:
    #      userId:
    #        referencedColumnName: id
    #    inverseJoinColumns:
    #      cityId:
    #        referencedColumnName: id
    roles: # bidirectional @link http://goo.gl/83P2JC
      targetEntity: Agere\Role\Model\Role
      inversedBy: users
      joinTable:
        name: users_roles
        joinColumns:
          userId:
            referencedColumnName: id
        inverseJoinColumns:
          roleId:
            referencedColumnName: id
  manyToOne:
      pool:
        targetEntity: Agere\Pool\Model\Pool
        inversedBy: pool
        joinColumn:
          name: poolId
          referencedColumnName: id